project:
  type: website
  output-dir: docs

website:
  title: "João Bonifácio"
  site-url: "https://bonijoao.github.io"
  description: "Portfólio, Blog e Cientista de Dados | Especialista em R & Shiny"
  navbar:
    background: dark
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About"
      - href: pacotes/index.qmd
        text: R Packages
      - href: shiny/index.qmd
        text: Shiny Apps
    right:
      - icon: github
        href: https://github.com/bonijoao
      - icon: linkedin
        href: https://linkedin.com/in/seu-perfil
      - text: "<img src='/images/orcid.svg' style='width:18px;height:18px;vertical-align:-2px;' title='ORCID' />"
        href: https://orcid.org/0009-0009-2335-8391
      - text: "<img src='/images/lattes.png' style='width:18px;height:18px;vertical-align:-2px;' title='Lattes' />"
        href: http://lattes.cnpq.br/5140906846177048
      - text: ""
        href: "#"
        id: quarto-toggle-theme

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.scss
    page-layout: full
    embed-resources: true
 